import { City, RootWeatherData } from "./weather-service.model";

export const mockWeatherData: RootWeatherData = {
  location: {
    name: 'London',
    region: 'City of London, Greater London',
    country: 'United Kingdom',
    lat: 51.52,
    lon: -0.11,
    tz_id: 'Europe/London',
    localtime_epoch: 1685326781,
    localtime: '2023-05-29 3:19',
  },
  current: {
    last_updated_epoch: 1685326500,
    last_updated: '2023-05-29 03:15',
    temp_c: 9,
    temp_f: 48.2,
    is_day: 0,
    condition: {
      text: 'Clear',
      icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
      code: 1000,
    },
    wind_mph: 9.4,
    wind_kph: 15.1,
    wind_degree: 40,
    wind_dir: 'NE',
    pressure_mb: 1027,
    pressure_in: 30.33,
    precip_mm: 0,
    precip_in: 0,
    humidity: 76,
    cloud: 0,
    feelslike_c: 6.7,
    feelslike_f: 44,
    vis_km: 10,
    vis_miles: 6,
    uv: 1,
    gust_mph: 14.1,
    gust_kph: 22.7,
  },
  forecast: {
    forecastday: [
    ],
  },
};

export const mockCitiesData: Array<City> = [
  {
    id: 173459,
    name: 'Lagos',
    region: 'Lagos',
    country: 'Nigeria',
    lat: 6.45,
    lon: 3.44,
    url: 'lagos-lagos-nigeria',
  },
  {
    id: 3256200,
    name: 'Lagos De Moreno',
    region: 'Jalisco',
    country: 'Mexico',
    lat: 21.36,
    lon: -101.93,
    url: 'lagos-de-moreno-jalisco-mexico',
  },
  {
    id: 2003368,
    name: 'Lagos',
    region: 'Faro',
    country: 'Portugal',
    lat: 37.1,
    lon: -8.67,
    url: 'lagos-faro-portugal',
  },
];

export const mockCity: City = {
  id: 173459,
    name: 'Lagos',
    region: 'Lagos',
    country: 'Nigeria',
    lat: 6.45,
    lon: 3.44,
    url: 'lagos-lagos-nigeria',
}

export const mockHourlyWeather = {
    time_epoch: 100,
    time: 'GTM 12:00pm',
    temp_c: 100,
    temp_f: 100,
    is_day: 100,
    condition: {
      text: 'string',
      icon: 'string',
      code: 3
    },
    wind_mph: 100,
    wind_kph: 100,
    wind_degree: 100,
    wind_dir: 'string',
    pressure_mb: 100,
    pressure_in: 100,
    precip_mm: 100,
    precip_in: 100,
    humidity: 100,
    cloud: 100,
    feelslike_c: 100,
    feelslike_f: 100,
    windchill_c: 100,
    windchill_f: 100,
    heatindex_c: 100,
    heatindex_f: 100,
    dewpoint_c: 100,
    dewpoint_f: 100,
    will_it_rain: 100,
    chance_of_rain: 100,
    will_it_snow: 100,
    chance_of_snow: 100,
    vis_km: 100,
    vis_miles: 100,
    gust_mph: 100,
    gust_kph: 100,
    uv: 100,
  }
